baseURL = "https://engineering.redislabs.com/"
languageCode = "en-us"
title = "Redis Labs Engineering Blog"
theme = "minimal-bootstrap-hugo-theme"
pygmentsCodeFences = true
# pygmentsStyle = "friendly"
# pygmentsStyle = "github"
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  logo="favicon-32x32.png"
  description = "Redis Labs Engineering Blog"
  # contentBackgroundColor = "#fff"
  contentTextColor = "#494C4D"
  contentLinkColor = "#6592B8"
  contentLinkHoverColor = "#354253"
  navbarBackgroundColor = "#354253"
  # navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  # navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  # wrapperMaxWidth = "800px"
  # customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  # showPostSummary = false
  googleAnalytics = "UA-92003007-13"
  googleTagManager = "GTM-N6FJFFK"
  # cookieConsent = true
  # includeBootstrapJs = false
  # faviconSafariPinnedTabColor = "#5bbad5"
  # faviconMsApplicationTileColor = "#da532c"
  # faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Engineering Blog"
  url = "/"
  weight = 1

  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 2

#  [[menu.nav]]
#  name = "About"
#  url = "/about/"
#  weight = 3

  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 4
